### ISSUE TITLE
Set drawer as manual toggle

### ISSUE THREAD

**Issue by Fenrirthviti** [alexbananabob/dashboard#14]
Hello! I'm loving the template, but having a hell of a time trying to figure out how to make the drawer/header start open, but allow a manual toggle to close/reopen while still following the normal screen size changes (i.e. auto-hide the drawer if the browser falls below a certain size, etc.). The default state based on screen size is fine, but for some of the content I am serving through the site (streaming video), I want users to be able to manually close the drawer for more screen space.

Is this something that would be possible with your template?

I am happy to provide any additional details as needed if what I am requesting was not explained well enough.

**Comment by alexbananabob** [comment]
Hi, Fenrirthviti! If you want show/hide drawer only by click on the button on top left corner, you can override variable _$layout-screen-size-threshold_ in _src/variables.scss_ more than 5000px or more. 
But the initial state of page(after load, reload) will be with hidden drawer.

Hope, i helped you, but if not, you can ask me again. Good luck!

**Comment by Fenrirthviti** [comment]
No, that's not really what I'm looking for. I'm able to have the behavior you described through changing the classes of the layout itself and following the MDL standards.

Currently, the page loads with the drawer open, but not as an overlay, which affects the layout of the whole page. When it becomes hidden, the functions to show/hide the drawer only function as an overlay. I am looking for a hide/show function available at any time that will toggle the drawer being open in the non-overlay state.

**Comment by alexbananabob** [comment]
Okey, i'm understood. Try to look to side `<div class="mdl-layout__obfuscator"></div>` - this is overlay div. Then try set margin-left = 0 in layout.scss(check media queries) for `<main class="mdl-layout__content">`. And then you need always show hide/show button

**Comment by Fenrirthviti** [comment]
I'll try that out, thanks! Will have to make the jump to use the .scss files instead of the pre-compiled version in /dist that I have been using. Not too familiar with Sass in general, and I really don't want to use node for my project. But that should be enough to point me in the right direction!
