### ISSUE TITLE
Sub menu

### ISSUE THREAD

**Issue by mattdeveluk** [alexbananabob/dashboard#16]
It would be great if there would be possibility of creating sub menus in navigation, such as  [there is](http://demo.tb3.co.in/mdl/mdlAdmin-lite/#/).

**Comment by prediator** [comment]
I have done it at my end locally. I need to contribute.

**Comment by franckevva** [comment]
@prediator It would be great if you can share your decision. Please create a pull request

**Comment by mattdeveluk** [comment]
@prediator Pull request would be great, or if you could post it on jsfiddle or codepen.

**Comment by prediator** [comment]
sorry guys i am new to pull request. I have submitted a pull request.

**Comment by alexbananabob** [comment]
Thanks guys! Good suggestion. Perhaps, we will add this feature in the next milestone.
