### ISSUE TITLE
material-dashboard-lite-rtl

### ISSUE THREAD

**Issue by mmdsharifi** [alexbananabob/dashboard#18]
Hi ,
Thanks for this great work, I recently make it RTL : 
https://github.com/mmdsharifi/material-dashboard-lite-rtl/tree/master 

but as you see nav menu not display correctly, for example avatar drop down menu :

![issue](https://cloud.githubusercontent.com/assets/6915384/18262931/4898633a-741b-11e6-8f71-5fbcd3dfa0b7.PNG)

I know this issue happen by injection JavaScript style, what is best solution?

With regards Mohammad Sharifi

**Comment by alexbananabob** [comment]
Hello, Mohammad Sharifi! 
Now avatar dropdown menu align to right side using **.mdl-menu--bottom-right** class for '`<ul>`' element in mdl-menu. To align dropdown menu to left side you need simply remove this class
